### ISSUE TITLE
[Question] Is this a 2-way sync?

### ISSUE THREAD

**Issue by bugzy** [judell/zotero#1]
For instance:
1. Annotations from hypothesis are created as zotero child notes. (hypothesis-> zotero)
2. If I add new child notes to the same pdf on zotero, will the childnotes be created as new annotations on hypothesis? (zotero -> hypothesis)?

Here is some context so you get a better idea of what I am trying to do:
1. I create pdf annotations using my local pdf reader (ereader device, android device, or tablet).
2. I use [zotfile](http://zotfile.com/), a zotero plugin, to extract my locally generated annotations into child notes.
3. I use the contents of this repo to push my annotations up to my hypothesis account.

**Comment by judell** [comment]
No, it's only Hypothesis annotations -> Zotero child notes.

**Comment by bugzy** [comment]
I see. Thanks for the response
